[package]
name = "mnemos-bitslab"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true


[dependencies]
portable-atomic = { version = "1", default-features = false }

[dev-dependencies]
proptest = "1"