cargo-features = ["per-package-target", "profile-rustflags"]

[package]
name = "mnemos-x86_64-bootimager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
camino = "1"
libcrowtty = { path = "../libcrowtty" }
heck = "0.5"
# cargo_metadata = "0.18.1"
miette = { workspace = true, features = ["fancy"] }
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"
owo-colors = "4"
clap = { version = "4.5", features = ["derive", "env"] }
bootloader = "0.11"
bootloader-boot-config = "0.11.3"
# escargot = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "tracing-log"] }
tracing-log = "0.2"
supports-color = "3"
