MEMORY {
    RAM   : ORIGIN = 0x40000000, LENGTH = 128M
    AHEAP : ORIGIN = 0x48000000, LENGTH = 384M
}

REGION_ALIAS("REGION_TEXT", RAM)
REGION_ALIAS("REGION_RODATA", RAM)
REGION_ALIAS("REGION_DATA", RAM)
REGION_ALIAS("REGION_BSS", RAM)
REGION_ALIAS("REGION_HEAP", RAM)
REGION_ALIAS("REGION_STACK", RAM)

_aheap_start = ORIGIN(AHEAP);
_aheap_size = LENGTH(AHEAP);
