
cargo-features = ["per-package-target", "profile-rustflags"]

[package]
name = "mnemos-d1-core"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true


[features]
# enable the SHARP Memory Display driver
sharp-display = []

[dependencies]
serde = { version = "1.0.178", features = ["derive"], default-features = false }
mnemos-bitslab = { path = "../../../source/bitslab" }
mycelium-bitfield = "0.1.3"

d1-pac = "0.0.31"
critical-section = "1.1.1"

[target.'cfg(any(target_arch = "riscv64", target_arch = "riscv32"))'.dependencies]
riscv = "0.10.0"
riscv-rt = "0.11"

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
default-features = false

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
default-features = false

[dependencies.embedded-graphics]
version = "0.7.1"

[dependencies.futures]
version = "0.3.21"
features = ["async-await"]
default-features = false

[dev-dependencies]
proptest = "1"
proptest-derive = "0.4.0"