MEMORY {
    RAM   : ORIGIN = 0x40000000, LENGTH = 512M
}

REGION_ALIAS("REGION_TEXT", RAM)
REGION_ALIAS("REGION_RODATA", RAM)
REGION_ALIAS("REGION_DATA", RAM)
REGION_ALIAS("REGION_BSS", RAM)
REGION_ALIAS("REGION_HEAP", RAM)
REGION_ALIAS("REGION_STACK", RAM)
