cargo-features = ["per-package-target", "profile-rustflags"]

[package]
name = "melpomene"
version = "0.1.0"
edition = "2021"
description = """
A desktop simulator, suitable for experimenting with MnemOS without
any external hardware requirements.
"""
repository = "https://github.com/tosc-rs/mnemos"
homepage = "https://mnemos.dev"
readme = "./README.md"
license = "MIT OR Apache-2.0"

[build-dependencies]
melpo-config = { path = "./melpo-config" }
serde = { version = "1.0.178", features = ["derive"] }
mnemos-config = { path = "../../source/config", features = ["use-std"] }
mnemos-kernel = { package = "mnemos", path = "../../source/kernel" }

[dependencies]
serde = { version = "1.0.178", features = ["derive"] }
melpo-config = { path = "./melpo-config" }
mnemos-config = { path = "../../source/config" }

[dependencies.tracing]
version = "0.1.35"

[dependencies.tracing-subscriber]
version = "0.3.14"
features = ["registry", "fmt", "ansi"]
default-features = false

[dependencies.tracing-modality]
# version = "0.1.1"
optional = true
git = "https://github.com/auxoncorp/modality-tracing-rs"
rev = "9c23c188466357e7ad0c618b4edfe9514e9bf764"

[dependencies.uuid]
version = "1.1.2"
default-features = false
features = ["serde"]

[dependencies.mnemos-kernel]
package = "mnemos"
path = "../../source/kernel"

[dependencies.mnemos-alloc]
version = "0.1.0"
features = ["use-std"]
path = "../../source/alloc"

[dependencies.mnemos-abi]
path = "../../source/abi"

[dependencies.mnemos-std]
path = "../../source/mstd"

[dependencies.postcard]
version = "1.0.1"
default-features = false

[dependencies.atty]
version = "0.2"
optional = true

[dependencies.console-subscriber]
version = "0.1.6"
optional = true

[dependencies.tokio]
version = "1.19"
features = ["rt", "rt-multi-thread", "time", "macros", "sync"]

[dependencies.clap]
version = "3.0"
features = ["env", "derive"]

[dependencies.humantime]
version = "2"
optional = true

[dependencies.embedded-graphics]
version = "0.7.1"

[dependencies.embedded-graphics-simulator]
version = "0.3.0"

[dependencies.chrono]
version = "0.4"

# Melpomene does not use any APIs from `maitake` directly. This dependency is
# instead required in order to enable `maitake`'s support for `tracing` 0.1.x,
# which is needed to support the Tokio Console while running in the simulator,
# but is not needed by actual builds of mnemOS running on real hardware.
[dependencies.maitake]
version = "0.1.0"
features = ["tracing-01"]

[dependencies.forth3]
path = "../../source/forth3"
features = ["async"]

[dependencies.futures]
version = "0.3"
default-features = false
features = ["std", "async-await"]

[features]
# enables Tokio Console support
trace-console = ["console-subscriber", "humantime"]
trace-fmt = ["tracing-subscriber/fmt", "atty"]
# Note, the "trace-modality" feature requires the use of the Auxon modality tool.
# More information: https://auxon.io/products/modality
trace-modality = ["tracing-modality", "tokio/net", "tokio/sync"]
default = ["trace-console", "trace-fmt"]
