[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

# this isn't technically the correct target --- it *should* be
# `riscv32-imc-unknown-none-elf`. but, because we're using the
# `riscv-atomic-emulation-trap` crate, we want to emit these instructions, and
# just setting `target_has_atomic` in `rustflags` makes `portable-atomic` not
# compile, since it does feature detection based on both `cfg_target_has_atomic`
# *and* the target triple. oh well.
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]