cargo-features = ["per-package-target", "profile-rustflags"]

[package]
name = "mnemos-esp32c3-buddy"
version = "0.1.0"
authors = [
    "Eliza Weisman <eliza@elizas.website>",
    "James Munns <james@onevariable.com>",
]
edition = "2021"
repository = "https://github.com/tosc-rs/mnemos"
homepage = "https://mnemos.dev"
readme = "./README.md"
license = "MIT OR Apache-2.0"

# this isn't technically the correct target --- it *should* be
# `riscv32-imc-unknown-none-elf`. but, because we're using the
# `riscv-atomic-emulation-trap` crate, we want to emit these instructions, and
# just setting `target_has_atomic` in `rustflags` makes `portable-atomic` not
# compile, since it does feature detection based on both `cfg_target_has_atomic`
# *and* the target triple. oh well.
forced-target = "riscv32imac-unknown-none-elf"

[lib]
test = false
bench = false

[[bin]]
name = "qtpy"
test = false
bench = false

[[bin]]
name = "xiao"
test = false
bench = false

[dependencies]
critical-section = "1"
esp32c3-hal = "0.12.0"
esp-alloc = "0.3"
embassy-net-driver-channel = "0.1.0"
riscv = "0.10.1"

[dependencies.esp-backtrace]
version = "0.7.0"
features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"]

[dependencies.esp-println]
version = "0.5.0"
features = ["esp32c3"]

[dependencies.esp-wifi]
git = "https://github.com/esp-rs/esp-wifi/"
rev = "fbb8417fc450ec0701067b36629770c11338231c"
default-features = false
features = [
    "wifi",
    "ipv6",
    "esp32c3",
    # needed for usb-serial debugging. this should be disabled if/when we are no
    # longer using usb-serial, as it can impact wifi performance.
    #
    # see here for details:
    # https://github.com/esp-rs/esp-wifi/tree/fbb8417fc450ec0701067b36629770c11338231c#usb-serial-jtag
    "phy-enable-usb",
]

[dependencies.portable-atomic]
version = "1.4"
default-features = false
features = ["critical-section"]

# kernel
[dependencies.mnemos]
path = "../../source/kernel"
features = ["serial-trace"]

[dependencies.tracing]
version = "0.1.37"
# branch = "master"
features = ["attributes"]
default-features = false

[dependencies.futures]
version = "0.3.21"
default-features = false
features = ["async-await"]